### ISSUE TITLE
LOT_SIZE unhandled error

### ISSUE THREAD

**Issue by linucis** [Dylan-Kerler/Binance-MM-JS#1]
exit after executing.

$./binance_market_maker_js.sh --apiKey=xxxx --apiSecret=xxxx --spread=3 --exposure=2 --base=BTC --stock=ETH

        Running market maker with the following options;
        Spread: 0.001
        Exposure: 0.001
        Base Asset: BTC
        Stock Asset: ETH
    
Initialising...

        Entering orders:
            Buy amount (BTC): 0.00001
            Buy price (BTC): 0.02049

            Sell amount (ETH): 0.00000
            Sell price (ETH): 0.02051

            Last Price: 0.020497 
        
(node:8024) UnhandledPromiseRejectionWarning: Error: Filter failure: LOT_SIZE
    at /home/ubuntu/Binance-Market-Maker-JS/node_modules/binance-api-node/dist/http-client.js:59:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async recalculate_and_enter (/home/ubuntu/Binance-Market-Maker-JS/src/main.js:109:27)
(node:8024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Dylan-Kerler** [comment]
What is your account balance?
`Sell amount (ETH): 0.00000`

looks like it is too small. It is less than the minimum order size.

**Comment by linucis** [comment]
My binance balance:
BTC : 0.00628529
ETH : 0.30569400

I'm just testing your code and I don't know how 
calculations works in exposure and spreads.
I think your program is specific on Github and needs to be worked out more.

**Comment by Dylan-Kerler** [comment]
The calculation is based on your available balance * exposure / 100.
`0.30569400 * 3 / 100 =  0.00611388`

```javascript
const stock_balance = parseFloat(account_info.balances.find(asset_obj => asset_obj.asset == opts.stock).free);
const quantity_stock = (stock_balance * opts.exposure).toFixed(5);
```

Did you have any open orders before you ran the bot? Those orders will not have been included in your available balance.

**Comment by linucis** [comment]
Yes. I did open some orders before ran the bot.
would you please mention the minimum amount in balance? BTC or ETH or what?

**Comment by Dylan-Kerler** [comment]
The minimum amount in balance would be: `min_order_size / (exposure / 100)`. You can find the minimum order size for each asset here: https://www.binance.com/en/trade-rule.

So for example, let's say you want to trade ETHBTC with an exposure of 1%. This is how you would calculate the amount of BTC balance that you would need:
`0.0001 / (1 / 100) = 0.01 BTC`. 

In order for this to work you need at least 0.01 BTC in your available balance (if you have BTC in open orders already then they will not be included in your available balance). The same applies for ETH:
`0.001 / (1 / 100) = 0.01 ETH = 0.1 ETH`.

The key thing here is that if you have `x` amount of an asset in open orders then your available balance becomes `total_balance - x`.
